print("A new patient came in what is their name, Age, and is he new or reccuring?")
print("What is their name?")
name = input()
print("Their name is " + name + '.')  
print("What is their age?")
age = input()
print('They are ' + age + '.')
print('Are they a new or reccuring?')
status = input()
print("They are a " + status + ' patient.')
print("We checked in a patient named " + name + '.')
print("He's " + age + " years old and is a " + status + ' patient.')